server:
  port: 8080
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud: DEBUG
spring:
  application:
    name: products

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
  instance:
    #preferIpAddress: true
    hostname: localhost
